name: Build and push Docker images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    
    - name: Build Dockerfile
      run: |
        docker build -t gcr.io/hack-hsp-infinities/php_app:${{ github.run_number }} .
  
    - name: Push Docker image
      run: |
        docker push gcr.io/hack-hsp-infinities/php_app:${{ github.run_number }}
        
